#!/bin/bash

# mail_fetch: fetch new messages in my Gmail account with a provided mail sender, also manaage a database for processed mail deduplication and continous work without overlap time
# Usage: mail_fetch <sender>, this <sender> doesn't need to be a full mail address, it can be part of address, ex. a postfix from `@` like `@gmail.com`, etc
# Notes: max fetching number is: 20

set -e

HOME_DIR=$(cd "$(dirname "$0")/.." &> /dev/null && pwd)
BIN_DIR="$HOME_DIR/bins"
DB_PATH="$HOME_DIR/data/mails_monitor.db"

sender=$1

# fetch last execution time
new_time=$(date +"%Y-%m-%d %H:%M:%S")
echo "start to fetch at $new_time"

last_time=$(sqlite3 $DB_PATH "SELECT last_scan_time FROM scan_state WHERE sender = '$sender' LIMIT 1;")
if [[ -z "$last_time" ]]; then
  # default fech from 3 days ago
  last_time=$(date -d "-3 days" +"%Y/%m/%d %H:%M:%S")
fi
last_day=$(date -d "$last_time" +"%Y/%m/%d")
echo "checking mails from:$sender after:$last_day" 

# fech new emails
gog gmail messages search "from:$sender after:$last_day" --max 20 --json --account $GOG_ACCOUNT | jq -c '.messages[]' | while read -r item; do
  message_id=$(echo $item | jq -r '.id')
  # skip if already processed before
  processed=$(sqlite3 $DB_PATH "SELECT COUNT(*) FROM processed_emails WHERE message_id = '$message_id';")
  if [ "$processed" -gt 0 ]; then
    continue
  fi

  # fetch mail details
  echo "found new mail:$message_id"
  message_content=$(gog gmail get $message_id --json --account $GOG_ACCOUNT)
  message_subject=$(echo $message_content | jq -r '.headers.subject' | sed "s/'/\\\\'/g")
  message_sender=$(echo $message_content | jq -r '.headers.from' | sed "s/'/\\\\'/g")
  message_date=$(echo $message_content | jq -r '.headers.date')

  # insert to processed_emails table
  query="INSERT OR IGNORE INTO processed_emails (message_id, subject, sender, received_at) VALUES (?, ?, ?, ?)"
  $BIN_DIR/sqlite3_exec "$DB_PATH" "$query" "$message_id" "$message_subject" "$message_sender" "$message_date"
  # save email content to file
  echo $message_content > "/tmp/$message_id.json"
  python3 $BIN_DIR/mail_extract "/tmp/$message_id.json" "/tmp/$message_id.txt"
done

# update last_scan_time
$BIN_DIR/sqlite3_exec "$DB_PATH" "UPDATE scan_state SET last_scan_time = ? WHERE sender = ?", "$new_time" "$sender"
